---
- name: Playbook using change_create_bitbucket role
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute change_create_bitbucket role
      block:
        - include_role:
            name: isp.change.change_create_bitbucket