---
- name: Playbook using change_create_bitbucket role
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Execute change_create_bitbucket role
      block:
        - name: change_create_bitbucket
          include_role:
            name: isp.change.change_create_bitbucket
      rescue:
        - set_stats:
            data:
            error_code: "{{ error_code }}"